[project]
ref = "hvihsarnclxnwecpahfa"

[functions.ig-refresh]
verify_jwt = false

[schedules.ig_refresh_cron]
cron = "0 */12 * * *"
endpoint = "ig-refresh"

[functions.ig-sync-media]
verify_jwt = false

[schedules.ig_sync_media_cron]
cron = "0 */6 * * *"
endpoint = "ig-sync-media"