project_id = "hvihsarnclxnwecpahfa"

[functions.supabase-functions-toml-writer]
verify_jwt = false

[functions.ig-refresh]
verify_jwt = false

[functions.ig-sync-media]
verify_jwt = false

# 每 12 小時跑一次
[schedules.ig_refresh_cron]
cron = "0 */12 * * *"
endpoint = "ig-refresh"

# 每 6 小時跑一次
[schedules.ig_sync_media_cron]
cron = "0 */6 * * *"
endpoint = "ig-sync-media"