# supabase.toml（專案根目錄）
[functions.supabase-functions-toml-writer]
verify_jwt = false

[functions.ig-refresh]
verify_jwt = false

[functions.ig-sync-media]
verify_jwt = false

# ── 排程設定 ──
[schedules.ig_refresh_cron]
cron = "0 */12 * * *"     # 每 12 小時
endpoint = "ig-refresh"

[schedules.ig_sync_media_cron]
cron = "0 */6 * * *"      # 每 6 小時
endpoint = "ig-sync-media"